### PR TITLE
Chinese food

### PR DESCRIPTION
**Pull request by 0CreepySmile0**

### CODE REVIEW

**Comment by TeerapatTrepopsakulsin** [comment]
Please add a link for navigation

**Comment by OmegaOoh** [comment]
image file should be jpg/png, it shouldn't be webp. also please rename the file to be more readable

**Review by opxz7148 — CHANGES_REQUESTED** [review]
Food name are bold pls fix

**Comment by TeerapatTrepopsakulsin** [comment]
Change the Chinese section header to be:
Cuisine | Description | Picture | Price

**Review by opxz7148 — APPROVED** [review]
lgtm

**Review by OmegaOoh — APPROVED** [review]
Just change the table header and you're good to go

**Pull request merged**
